kevin-lee/just-sysprocess

- .github/workflows/release.yml
Enabled: GitHub Actions - sync to Maven Central in `release.yml`
> Enabled: GitHub Actions - sync to Maven Central in release.yml

- README.md
> Added: Badges

- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
* Upgraded: Scala 2.12.11 => 2.12.12 / 2.13.2 => 2.13.3
* Added: sbt-updates to detect library update
> Upgrade Scala and add sbt-updates

- .github/workflows/build.yml
- build.sbt
- src/main/scala/just/sysprocess/SysProcess.scala
Upgraded: Scala 2.12.11 => 2.12.12 / 2.13.2 => 2.13.3 in `build.yml`
> Upgraded: Scala 2.12.11 => 2.12.12 / 2.13.2 => 2.13.3 in build.yml

- .github/workflows/build.yml
- .github/workflows/maven_central_sync.sh
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- README.md
- build.sbt
- project/plugins.sbt
> Close #12 - Support Dotty

- changelogs/0.1.0.md
- changelogs/0.2.0.md
- project/ProjectInfo.scala
> just-sysprocess v0.2.0

- .github/workflows/release-specific.yml
- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
* Updated: Dotty 0.26.0-RC1 => 0.26.0
* Added: Dotty 0.27.0-Rc1
* Added: GitHub Actions config to release specific versions
> Updated: Dotty / Added: GitHub Actions config to release specific versions

- .github/workflows/build.yml
- .github/workflows/release-specific.yml
- .github/workflows/release.yml
- .gitignore
- build.sbt
- project/build.properties
- project/plugins.sbt
* sbt-dotty 0.4.2 => 0.4.6
* sbt 1.3.13 => 1.4.2
* sbt-docusaur 0.1.1 => "0.3.0
> Close #18 - Support Scala 3.0.0-M1

- .github/workflows/release-specific.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
Added: `SOURCE_DATE_EPOCH` env var in GitHub Actions config files
> Added: SOURCE_DATE_EPOCH env var in GitHub Actions config files

- project/build.properties
> Upgraded: sbt 1.4.2 => 1.4.3

- .github/workflows/build.yml
- .github/workflows/release-specific.yml
- .github/workflows/release.yml
- build.sbt
Close #24 - Support Scala `3.0.0-M2`
> Close #24 - Support Scala 3.0.0-M2

- project/build.properties
> Upgraded: sbt 1.4.3 => 1.4.4

- .github/workflows/build.yml
- .github/workflows/release-specific.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- build.sbt
- project/plugins.sbt
Upgraded: Scala 2.13.3 => 2.13.4
> Upgraded: Scala 2.13.3 => 2.13.4

- .github/workflows/release-specific.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
Fixed: a bug in build script - may cause the wrong timestamp for artifacts
> Fixed: a bug in build script - may cause the wrong timestamp for artifacts

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Close #29 - Support Scala `3.0.0-M3`
> Close #29 - Support Scala 3.0.0-M3

- project/build.properties
> Upgraded: sbt 1.4.4 => 1.4.6

- project/build.properties
> Upgraded: sbt 1.4.6 => 1.4.9

- .github/workflows/build.yml
- .github/workflows/release-specific.yml
- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Close #33 - Support Scala `3.0.0-RC1`
> Close #33 - Support Scala 3.0.0-RC1

- .github/workflows/manual-github-release.yml
- .github/workflows/manual-github-upload-and-publish.yml
- .github/workflows/maven_central_sync.sh
- .github/workflows/release.yml
Upgraded: GitHub Actions build and release configs
> Upgraded: GitHub Actions build and release configs

- .github/workflows/build.yml
- build.sbt
Close #39 - Support Scala 3.0.0-RC2
> Close #39 - Support Scala 3.0.0-RC2

- .scalafmt.conf
- src/main/scala/just/sysprocess/SysProcess.scala
- src/test/scala/just/sysprocess/SysProcessSpec.scala
Added: `.scalafmt.conf` and formatted
> Added: .scalafmt.conf and formatted

- .github/workflows/build.yml
Removed: GitHub Actions build for PRs
> Removed: GitHub Actions build for PRs

- build.sbt
- project/build.properties
- project/plugins.sbt
Close #45 - Support Scala 3.0.0-RC3
> Close #45 - Support Scala 3.0.0-RC3

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- build.sbt
Close #50 - Support Scala 3.0.0
> Close #50 - Support Scala 3.0.0

- README.md
Updated: `README.md` with new version info
> Updated: README.md with new version info

- project/plugins.sbt
Upgraded: sbt plugins
- `sbt-devoops` `2.3.0` => `2.10.0`
- `sbt-docusaur` `0.5.0` => `0.7.0`
> Upgraded: sbt plugins

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/task-template.md
> Added: GitHub issue templates

- .github/PULL_REQUEST_TEMPLATE.md
> Added: A GitHub PR template

- src/main/scala/just/sysprocess/SysProcess.scala
- src/test/scala/just/sysprocess/SysProcessSpec.scala
> Close #57 - Simplify API

- project/build.properties
Upgraded: sbt `1.5.2` => `1.5.5`
> Upgraded: sbt 1.5.2 => 1.5.5

- .scalafmt.conf
- build.sbt
- src/main/scala-2/just/sysprocess/SysProcess.scala
- src/main/scala-3/just/sysprocess/SysProcess.scala
- src/test/scala/just/sysprocess/SysProcessSpec.scala
Close #58 - Write code for Scala 3 using Scala 3 syntax
> Close #58 - Write code for Scala 3 using Scala 3 syntax

- changelogs/1.0.0.md
* Simplify API (#57)
* Write code for Scala 3 using Scala 3 syntax (#58)
> just-sysprocess v1.0.0

- .github/dependabot.yml
Added: `dependabot.yml` for GitHub Actions
> Added: dependabot.yml for GitHub Actions

- project/build.properties
Upgraded: sbt `1.5.5` => `1.5.6`
> Upgraded: sbt 1.5.5 => 1.5.6

- project/build.properties
> Upgraded: sbt 1.5.6 => 1.6.1

- project/plugins.sbt
Upgrade: sbt plugins - sbt-devoops `2.14.0` => `2.15.0`
> Upgrade: sbt plugins - sbt-devoops 2.14.0 => 2.15.0

- build.sbt
- project/plugins.sbt
Close #75 - Publish to `s01.oss.sonatype.org` (the new Maven central)
> Close #75 - Publish to s01.oss.sonatype.org (the new Maven central)

- .scalafmt.conf
Update: .scalafmt.conf - 3.0.0 => 3.3.3 and rule update
> Update: .scalafmt.conf - 3.0.0 => 3.3.3 and rule update

- build.sbt
> Update: minor config change

- project/plugins.sbt
Upgrade: `sbt-devoops` `2.15.0` => `2.16.0`
> Upgrade: sbt-devoops 2.15.0 => 2.16.0

- .scalafmt.conf
Update: .scalafmt.conf - `3.3.3` => `3.4.3` / add one more `Term.ApplyInfix` for `->`
> Update: .scalafmt.conf - 3.3.3 => 3.4.3 / add one more Term.ApplyInfix for ->

- project/plugins.sbt
Upgrade sbt-devoops `2.19.0` => `2.22.0`
> Upgrade sbt-devoops `2.19.0` => `2.22.0`

- project/build.properties
- project/plugins.sbt
Bump sbt `1.7.1` => `1.7.3` and sbt-devoops `2.22.0` => `2.23.0`
> Bump sbt 1.7.1 => 1.7.3 and sbt-devoops 2.22.0 => 2.23.0

- project/build.properties
Upgrade: sbt 1.8.0-RC1 => 1.8.0
> Upgrade: sbt 1.8.0-RC1 => 1.8.0

- project/build.properties
> Upgrade: sbt 1.8.0 => 1.9.7

- build.sbt
- project/build.properties
- project/plugins.sbt
Bump sbt and plugins
* sbt to 1.9.8
* sbt-docusaur to 0.15.0
* sbt-devoops to 3.0.0
> Bump sbt and plugins

- project/plugins.sbt
> Add sbt-devoops-starter

- project/plugins.sbt
> Bump sbt-devoops to 3.1.0

- project/plugins.sbt
> Bump sbt-docusaur to 0.16.0

- project/build.properties
> Bump sbt to `1.10.11`

- .scalafmt.conf
Bump scalafmt version to 3.9.4
> Bump scalafmt version to 3.9.4

- build.sbt
- project/plugins.sbt
- Apply code formatting changes in build.sbt.
- Remove unnecessary `final` keywords from val definitions within the `props` object.
> Apply code formatting and remove final keywords
